<?php

function cipher_menu(){
    $items = array();
    $items['cipher'] = array(
        'title' => 'Encode a message with the Cipher',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('cipher_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    $items['cipher_result'] = array(
        'title' => 'Encode a message with the Cipher',
        'page callback' => 'display_cipher',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function cipher_form(){
    $form['shift_value'] = array(
        '#title' => 'Shift Value',
        '#type' => 'textfield',
        '#description' => 'The number of places to shift your letters (1-25)'
    );
    $form['shift_direction'] = array(
        '#title' => 'Shift Direction',
        '#type' => 'textfield',
        '#description' => 'The direction to shift (left/right)'
    );
    $form['message'] = array(
        '#title' => 'Message',
        '#type' => 'textfield',
        '#description' => 'The secret message to encode'
    );
    $form['submt'] = array(
        '#type' => 'submit',
        '#value' => 'Encode the Message'
    );
    return $form;
}

function cipher_form_submit($form, &$form_state) {
    $form_state['redirect'] = 'cipher_result';
}

function display_cipher() {
    return 'you did a thing!';
}
